name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform format
      run: terraform fmt -check

    - name: Terraform validate
      run: terraform validate

    - name: Terraform plan
      run: terraform plan -var-file=settings.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -var-file=settings.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.TF_API_TOKEN }}
